# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0kwyl7dbkniqvjhpill08sic2yfkzmvw1960qp35r3w5va4rmadj";
    x86_64-linux = "144f7xij16adlcz6xdavvp0jx7d1z7f685gyha5aygawlb3l9a1p";
    aarch64-linux = "0m1pbwb5hdvh5myh9zm1759k5czvj7qxvmiz3ihnnxgyl2wx10jv";
    x86_64-darwin = "1krklwfyn436m619sj0jkspa3q4zln27nj35ayg5xzaf035i3b7p";
    aarch64-darwin = "12rad4y8aada23027cks36giib37j11lw3z0apsmi7javmngcsak";
  };

  urlMap = {
    i686-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.1/clockify-cli_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.1/clockify-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.1/clockify-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.1/clockify-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.1/clockify-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "clockify-cli";
  version = "0.56.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clockify-cli $out/bin/clockify-cli
  '';

  system = system;

  meta = {
    description = "A simple cli to manage your time entries on Clockify from terminal";
    homepage = "https://clockify-cli.netlify.app/";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
    mainProgram = "./clockify-cli";

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
