# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "1wbz3qk2jpyizn4198g07lkrd7vhsgxq23ifnm0ndyh4lb3gjgc2";
    x86_64-linux = "0fyw6bazq09zxycpyg1rhh3n4pc5fn34nzhsxr3ixh1lmq2cwgg0";
    aarch64-linux = "11b55ifghwp0xlpy2h84l3zblcbqjx58ij4bi963aq3bym81xqgg";
    x86_64-darwin = "1ggk2444zz5m0xxijqzlm9s31000harq89sa5qvavd8hi4vdi85f";
    aarch64-darwin = "0qfq2mnxbvfl5ihil3yjnw7fh4g5sfm5iiqv0dp1fql9pnlif19r";
  };

  urlMap = {
    i686-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "clockify-cli";
  version = "0.56.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clockify-cli $out/bin/clockify-cli
  '';

  system = system;

  meta = {
    description = "A simple cli to manage your time entries on Clockify from terminal";
    homepage = "https://clockify-cli.netlify.app/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
