# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "09a0ccvlv38kaablv2pf3pfzcc304vfqb3azd1gi7j41ixd5xa2d";
    x86_64-linux = "10lvgpgz66kghilppmkvy8j9zim2r04ajq0615bczpfx36dcqdsv";
    aarch64-linux = "1xj7x520jdlc4nrhaawgsxmlyjbw3wyka2n42ivblcnmwca1nlfm";
    x86_64-darwin = "16mp4rf8xx4zgpk0shlc7bw5j2mmq2l3mnn8a4ndrfbmsqkdn3g6";
    aarch64-darwin = "0k2l44pwykxk9pdkmaj2gp8hr65pygrcfk3rksn15kj6j5v2kaw4";
  };

  urlMap = {
    i686-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.56.0/clockify-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "clockify-cli";
  version = "0.56.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clockify-cli $out/bin/clockify-cli
  '';

  system = system;

  meta = {
    description = "A simple cli to manage your time entries on Clockify from terminal";
    homepage = "https://clockify-cli.netlify.app/";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
